# Add Valores Array- Morales Martínez Adriel Josué1951

In [1]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.55016104, 0.27751059, 0.87581537],
       [0.85885616, 0.03023286, 0.11913442],
       [0.58121787, 0.72623367, 0.05559378],
       [0.13135601, 0.02517802, 0.1398657 ]])

In [3]:
arr_ent = np.random.randint(10, size=(2,3))
arr_ent

array([[3, 8, 6],
       [7, 1, 0]])

In [5]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# Add Valores Array- Morales Martínez Adriel Josué1951

In [6]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [7]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.insert(arr_6,2, [1,2,4])

array([6, 6, 1, 2, 4, 6, 6, 6, 6, 6, 6, 6])

In [10]:
np.delete(arr_ent,0,axis=1)

array([[8, 6],
       [1, 0]])